# Cosmonic Control HTTPTrigger for the server-side-photon http-api component.
apiVersion: control.cosmonic.io/v1alpha1
kind: HTTPTrigger
metadata:
  name: ssp-httpapi
  namespace: cosmonic-system
spec:
  ingress:
    host: server-side-photon.localhost.cosmonic.sh
    paths:
      - pathType: Prefix
        path: /
  timeout: 300s
  replicas: 1
  template:
    spec:
      hostInterfaces:
        - namespace: wasi
          package: logging
          version: 0.1.0-draft
          interfaces:
            - logging
        - namespace: wasmcloud
          package: messaging
          version: "0.2.0"
          interfaces:
            - consumer
            - types
      components:
        - name: http-api
          image: ghcr.io/cosmonic-labs/server-side-photon/http-api:0.1.0
